server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: dev123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieu01bdvn@gmail.com
    # This is password in feature "app password" of gmail
    password: morg tomc qaym namb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secretKey: Xv1MsBY3sOf96Zefj4wJoYbqk9a4cs2Jz8ln+mOoDUEGp78E2Wy3TDGx/HfzZ9VB
