# config server port
server:
  port: 8088

# config spring datasource
spring:
  datasource:
    url: jdbc:mysql://root:QzsxLXCzlGsNWIfzRiuFVUnirKPZRgHj@switchback.proxy.rlwy.net:34125/railway
    username: root
    password: QzsxLXCzlGsNWIfzRiuFVUnirKPZRgHj
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieu01bdvn@gmail.com
    # This is password in feature "app password" of gmail
    password: dwle xmjw pjgg jzju
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

frontend:
  url: ${FRONTEND_URL}

cloudinary:
  cloud_name: dflwowhcc
  api_key: 494678424734132
  api_secret: vJhF_LgVIyZtilZDGVYaWmLxOns


# different configs
jwt:
  secretKey: Xv1MsBY3sOf96Zefj4wJoYbqk9a4cs2Jz8ln+mOoDUEGp78E2Wy3TDGx/HfzZ9VB
